import 'dart:io';

import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../../../core/di/injection.dart';
import '../../../../core/extensions/context_extensions.dart';
import '../../../../core/services/preference_service.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/widgets/app_button.dart';
import '../../../../core/widgets/compact_amount_text.dart';
import '../../../../core/widgets/glass_container.dart';
import '../../../../core/widgets/liquid_glass_app_bar.dart';
import '../../../../core/widgets/status_components.dart';
import '../cubit/event_detail_cubit.dart';
import '../cubit/event_detail_state.dart';
import '../widgets/event_detail_shimmer.dart';
import '../widgets/settlement_row.dart';

@RoutePage()
class ExportSettlePage extends StatefulWidget {
  final int eventId;

  const ExportSettlePage({super.key, required this.eventId});

  @override
  State<ExportSettlePage> createState() => _ExportSettlePageState();
}

class _ExportSettlePageState extends State<ExportSettlePage> {
  late final EventDetailCubit _cubit;
  bool _isExporting = false;

  @override
  void initState() {
    super.initState();
    _cubit = getIt<EventDetailCubit>()..loadEventDetail(widget.eventId);
  }

  @override
  void dispose() {
    _cubit.close();
    super.dispose();
  }

  Future<void> _exportCsv(EventDetailLoaded state) async {
    setState(() => _isExporting = true);

    try {
      final currencySymbol = getIt<PreferenceService>().currencySymbol;
      final buffer = StringBuffer();
      final event = state.event;

      // Event Info
      buffer.writeln('Event Summary');
      buffer.writeln('Name,${_escapeCsv(event.name)}');
      buffer.writeln('Category,${_escapeCsv(event.category)}');
      buffer.writeln('Status,${_escapeCsv(event.status)}');
      buffer.writeln(
          'Total Spend,$currencySymbol${event.totalSpent.toStringAsFixed(2)}');
      buffer.writeln();

      // Participants
      buffer.writeln('Participants');
      buffer.writeln('Name,Email,Role');
      for (final p in event.participants) {
        buffer.writeln(
            '${_escapeCsv(p.name)},${_escapeCsv(p.email ?? '')},${p.isOwner ? 'Owner' : 'Member'}');
      }
      buffer.writeln();

      // Expenses
      buffer.writeln('Expenses');
      buffer.writeln('Title,Paid By,Amount,Date');
      for (final exp in state.expenses) {
        buffer.writeln(
            '${_escapeCsv(exp.title)},${_escapeCsv(exp.paidByName)},$currencySymbol${exp.amount.toStringAsFixed(2)},${exp.date.toIso8601String()}');
      }
      buffer.writeln();

      // Settlements
      buffer.writeln('Settlements / Debts');
      buffer.writeln('From,To,Amount');
      for (final s in state.settlements) {
        buffer.writeln(
            '${_escapeCsv(s.fromParticipant.name)},${_escapeCsv(s.toParticipant.name)},$currencySymbol${s.amount.toStringAsFixed(2)}');
      }

      final dir = await getTemporaryDirectory();
      final file = File(
          '${dir.path}/expendly_split_${event.name.replaceAll(' ', '_').toLowerCase()}.csv');
      await file.writeAsString(buffer.toString());

      await Share.shareXFiles(
        [XFile(file.path)],
        text: 'Settlement summary for ${event.name}',
      );
    } catch (e) {
      if (mounted) {
        StatusComponents.showToast(
          context,
          message: 'Failed to export CSV',
          isError: true,
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isExporting = false);
      }
    }
  }

  Future<void> _sendEmailSummary(EventDetailLoaded state) async {
    final currencySymbol = getIt<PreferenceService>().currencySymbol;
    final event = state.event;
    final buffer = StringBuffer();

    buffer.writeln('Settlement Summary for ${event.name}\n');
    buffer.writeln(
        'Total Expenses: $currencySymbol${event.totalSpent.toStringAsFixed(2)}\n');

    if (state.settlements.isEmpty) {
      buffer.writeln('All balances are settled! No debts to clear.');
    } else {
      buffer.writeln('Pending Settlements:');
      for (final s in state.settlements) {
        buffer.writeln(
            '• ${s.fromParticipant.name} pays ${s.toParticipant.name}: $currencySymbol${s.amount.toStringAsFixed(2)}');
      }
    }

    buffer.writeln('\nGenerated by Expendly');

    final subject = Uri.encodeComponent('Settlement Summary: ${event.name}');
    final body = Uri.encodeComponent(buffer.toString());
    final url = Uri.parse('mailto:?subject=$subject&body=$body');

    if (await canLaunchUrl(url)) {
      await launchUrl(url);
    } else if (mounted) {
      StatusComponents.showToast(
        context,
        message: 'Could not open email client',
        isError: true,
      );
    }
  }

  String _escapeCsv(String value) {
    if (value.contains(',') || value.contains('"') || value.contains('\n')) {
      return '"${value.replaceAll('"', '""')}"';
    }
    return value;
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = context.colorScheme;

    final topInset = MediaQuery.of(context).padding.top;
    final headerPaddingTop = topInset + kToolbarHeight;

    return BlocProvider.value(
      value: _cubit,
      child: Scaffold(
        backgroundColor: colorScheme.surface,
        extendBodyBehindAppBar: true,
        appBar: LiquidGlassAppBar(
          onLeadingPressed: () => context.router.popForced(),
          titleText: context.l10n.exportAndSettle,
        ),
        body: BlocBuilder<EventDetailCubit, EventDetailState>(
          builder: (context, state) {
            if (state is EventDetailLoading || state is EventDetailInitial) {
              return Padding(
                padding: EdgeInsets.only(top: headerPaddingTop),
                child: const EventDetailShimmer(),
              );
            }

            if (state is EventDetailError) {
              return Padding(
                padding: EdgeInsets.only(top: headerPaddingTop),
                child: Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.error_outline,
                          color: AppColors.semanticRed, size: 48.w),
                      SizedBox(height: 16.h),
                      Text(
                        context.l10n.operationFailed,
                        style: context.customTypography.bodyLarge.copyWith(
                          color: colorScheme.onSurface,
                        ),
                      ),
                    ],
                  ),
                ),
              );
            }

            if (state is EventDetailLoaded) {
              final event = state.event;

              return ListView(
                padding: EdgeInsets.only(
                  left: 20.w,
                  right: 20.w,
                  top: headerPaddingTop + 16.h,
                  bottom: 32.h,
                ),
                children: [
                  // Summary GlassContainer
                  GlassContainer(
                    padding: EdgeInsets.all(20.w),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          context.l10n.settlementSummary.toUpperCase(),
                          style: context.customTypography.labelMediumMono,
                        ),
                        SizedBox(height: 16.h),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  context.l10n.totalExpense,
                                  style: context.textTheme.labelSmall?.copyWith(
                                    color: colorScheme.onSurfaceVariant,
                                  ),
                                ),
                                SizedBox(height: 4.h),
                                CompactAmountText(
                                  amount: event.totalSpent,
                                  style: context
                                      .customTypography.headlineMediumMonoBold
                                      .copyWith(color: colorScheme.onSurface),
                                ),
                              ],
                            ),
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.end,
                              children: [
                                Text(
                                  context.l10n.yourShare,
                                  style: context.textTheme.labelSmall?.copyWith(
                                    color: colorScheme.onSurfaceVariant,
                                  ),
                                ),
                                SizedBox(height: 4.h),
                                CompactAmountText(
                                  amount: event.userShare,
                                  style: context
                                      .customTypography.headlineMediumMonoBold
                                      .copyWith(color: colorScheme.primary),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),

                  SizedBox(height: 20.h),

                  // Debts to be Cleared Section
                  Text(
                    context.l10n.debtsToCleared.toUpperCase(),
                    style: context.customTypography.labelMediumMono,
                  ),
                  SizedBox(height: 12.h),

                  if (state.settlements.isEmpty)
                    GlassContainer(
                      padding: EdgeInsets.all(24.w),
                      child: Center(
                        child: Text(
                          'All balanced! No debts pending.',
                          style: context.customTypography.bodyMedium.copyWith(
                            color: colorScheme.onSurface,
                          ),
                        ),
                      ),
                    )
                  else
                    ...state.settlements.map(
                      (s) => Padding(
                        padding: EdgeInsets.only(bottom: 8.h),
                        child: SettlementRow(
                          settlement: s,
                          selectedParticipant: state.event.participants
                              .firstWhere((p) => p.isOwner,
                                  orElse: () => state.event.participants.first),
                        ),
                      ),
                    ),

                  SizedBox(height: 32.h),

                  // Actions
                  AppButton(
                    text: context.l10n.exportToCsv,
                    isLoading: _isExporting,
                    onPressed: () => _exportCsv(state),
                    variant: AppButtonVariant.primary,
                  ),
                  SizedBox(height: 12.h),
                  AppButton(
                    text: context.l10n.sendViaEmail,
                    onPressed: () => _sendEmailSummary(state),
                    variant: AppButtonVariant.outlined,
                  ),
                  SizedBox(height: 24.h),
                ],
              );
            }

            return const SizedBox.shrink();
          },
        ),
      ),
    );
  }
}
